### ISSUE TITLE
ClientsConfigFilter cannot be instantiated via Spring

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/j2e-pac4j#15]
the clientsFactory needs get its own setter. I guess this also requires a new patch release.

**Comment by mmoayyed** [comment]
In fact, I think this issue is really about making a pass at the entire codebase and find other filters that may need the same change.

**Comment by leleuj** [comment]
I'm in line with your proposal, but not with your PR: https://github.com/pac4j/j2e-pac4j/pull/14/files, see my comments, the master is now reserved for version 1.2.0 (based on pac4j v1.8). You can use the branch 1.1.x.

**Comment by mmoayyed** [comment]
If the issue is fixed in 1.2 and it seems like it is, let's keep working on 1.2 then.
