### ISSUE TITLE
Improve config handling in filters

### ISSUE THREAD

**Issue by victornoel** [pac4j/j2e-pac4j#34]
The filters have `setConfig()` methods, but they modify `ConfigSingleton`, I guess because of the way servlet filters are usually installed, i.e., via a configuration file and a `ConfigFactory`.

In cases where the filter are used programmatically (see for example pac4j/dropwizard-pac4j#12), it make no sense to use the `ConfigSingleton`.

I propose that we use only the `ConfigSingleton` in case the config is set via the servlet filter parameter `Pac4jConstants.CONFIG_FACTORY`, but not when it is set via `setConfig()`.
It won't change anything for users of the servlet filter I think, but still, since we break setConfig() behaviour, we may need to release a new major version.

An alternative would be to introduce a `setConfigOnly()`, but it would be a shame not to do it cleanly :)

**Comment by leleuj** [comment]
If you use J2E and Spring and define your filters via `DelegatingFilterProxy`, the proposed change will be a breaking one.

I slightly lean toward backward compatibility and the alternative solution.

**Comment by victornoel** [comment]
Ah yes, Spring will use the `setConfig` to inject the config object itself?
But in that case, you don't need the `ConfigSingleton`, right?

Anyway, let's do the hack and forget it, I don't really like the idea of singletons but as long as dropwizard-pac4j won't have any interactions with it, I should be happy :)

I will make a PR then.
