### ISSUE TITLE
Change Java EE Logo

### ISSUE THREAD

**Issue by sebargarcia** [pac4j/j2e-pac4j#38]
Please Change the j2e-pac4j logo, I think is more convenient to put Java EE logo instead
[https://agoncal.files.wordpress.com/2014/05/java_ee_logo_vert_v2.png](url)

See:
https://abhirockzz.wordpress.com/2014/06/01/whats-in-a-name-java-ee-j2ee/

**Comment by leleuj** [comment]
Good point! I'll do that when I find some time...

**Comment by sebargarcia** [comment]
I can do it if you want. :)

**Comment by leleuj** [comment]
Sure. Go ahead.

**Comment by leleuj** [comment]
Done
