### ISSUE TITLE
HttpServletRequestWrapper needed

### ISSUE THREAD

**Issue by mores** [pac4j/j2e-pac4j#44]
Implement methods:
   public String getRemoteUser()
   public java.security.Principal getUserPrincipal()
   public boolean isUserInRole( String role )
from javax.servlet.http.HttpServletRequestWrapper

**Comment by mores** [comment]
Should there be a new class that implements java.security.Principal or should an existing class implement java.security.Principal ?

**Comment by victornoel** [comment]
I've tackled this kind of question once in jax-rs-pac4j: https://github.com/pac4j/jax-rs-pac4j/blob/master/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsProfileManager.java

**Comment by leleuj** [comment]
I think we said something then: did we plan to move these classes back to the core?

**Comment by victornoel** [comment]
Yep, it would make sense to have the ProfileImpl from jax-rs-pac4j moved to pac4j-core.

**Comment by leleuj** [comment]
Cool. Would you mind opening an issue for that and handling it?

**Comment by victornoel** [comment]
@mores what is the use case for this sublcall of `HttpServletRequestWrapper` you want?

**Comment by mores** [comment]
@victornoel Most of my projects are JSF.
`javax.faces.context.FacesContext context = javax.faces.context.FacesContext.getCurrentInstance();
javax.faces.context.ExternalContext ectx = context.getExternalContext();
javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)ectx.getRequest();

String loggedInUser = request.getRemoteUser();`

if( ectx.isUserInRole( "root" ) )
{
           // do something special
}

**Comment by victornoel** [comment]
@mores and what happens when you do that currently?

**Comment by mores** [comment]
Currently these webs are protected by CAS. request.getRemoteUser() returns the user that logged into CAS,
isUserInRole will return true or false based on the roles of the user from CAS.

https://wiki.jasig.org/display/CASUM/HOWTO+utilize+javax.servlet.http.HttpServletRequest+isUserInRole(+java.lang.String+role+)

**Comment by victornoel** [comment]
@mores sorry, we misunderstand each other: why do you need `HttpServletRequestWrapper` and why does the current situation doesn't work? I don't see anything related to `HttpServletRequestWrapper` in the code you just showed and I'm not servlet expert, so I would like to clarify the use case for introducing this class :)

**Comment by mores** [comment]
@victornoel No worries. High level use case: Today I have many web apps protected by CAS that now need to port over to pac4j.  

Here is the CAS Wrapper: https://github.com/apereo/java-cas-client/blob/master/cas-client-core/src/main/java/org/jasig/cas/client/util/HttpServletRequestWrapperFilter.java

I am attaching a Pac4jHttpServletRequestWrapper that currently works for me.

[Pac4jHttpServletRequestWrapper.txt](https://github.com/pac4j/j2e-pac4j/files/1372155/Pac4jHttpServletRequestWrapper.txt)

**Comment by victornoel** [comment]
Is the idea that j2e-pac4j should replace the `HttpServletRequest` with a `HttpServletRequestWrapper` that returns the pac4j data for the methods you mention in the issue description?

**Comment by victornoel** [comment]
@mores and how do you inject it to be used instead of the original one?

**Comment by mores** [comment]
@victornoel - Filters are configured in web.xml....
`
<filter>
	<filter-name>HttpServletRequestWrapperFilter</filter-name>
	<filter-class>org.pac4j.HttpServletRequestWrapperFilter</filter-class>
</filter>
<filter-mapping>
	<filter-name>HttpServletRequestWrapperFilter</filter-name>
	<url-pattern>/main/*</url-pattern>
</filter-mapping>
`

Sorry, not sure how to format xml with this markdown.

**Comment by victornoel** [comment]
no problem, I updated your comment ;) (check out the source to see how to do it).

Ok, and would it be ok if the pac4j `SecurityFilter` was wrapping the `HttpServletRequest` by default or do you think it's better that it is in a specific filter as in you xml example?

**Comment by mores** [comment]
This is really a pac4j architecture question....at this point I am not qualified to answer.

Do I recall reading that pac4j can work with multiple profiles at once ? 
The Pac4jHttpServletRequestWrapper I uploaded only works with the AzureAdProfile.
Will a  Pac4jHttpServletRequestWrapper be able to work with ANY profile ?
What would the directory tree look like:
/protectedByAzure
/protectedByCAS
/protectedByOpenId

My instinct tells me that trying to configure all this in one SecurityFilter will get complex very quickly. 
It may be easier to configure with a separate filter. ( just my 2 cents )

```xml
<filter>
	<filter-name>AzureHttpServletRequestWrapperFilter</filter-name>
	<filter-class>org.pac4j.HttpServletRequestWrapperFilter</filter-class>
        <init-param>
                        <param-name>profile</param-name>
                        <param-value>Azure</param-value>
        </init-param>
</filter>
<filter-mapping>
	<filter-name>AzureHttpServletRequestWrapperFilter</filter-name>
	<url-pattern>/protectedByAzure/*</url-pattern>
</filter-mapping>


<filter>
	<filter-name>CasHttpServletRequestWrapperFilter</filter-name>
	<filter-class>org.pac4j.HttpServletRequestWrapperFilter</filter-class>
        <init-param>
                        <param-name>profile</param-name>
                        <param-value>CAS</param-value>
        </init-param>
</filter>
<filter-mapping>
	<filter-name>CasHttpServletRequestWrapperFilter</filter-name>
	<url-pattern>/protectedByCas/*</url-pattern>
</filter-mapping>
```

**Comment by victornoel** [comment]
Ok, I see your point. I was thinking we would simply do the following mapping:
 - getRemoteUser: I was thinking simply returning the main profile id
 - getUserPrincipal: return a principal based on the main profile
 - isUserInRole: based on all the roles of the all the profiles

@leleuj ?

**Comment by mores** [comment]
Another thing to think about, while working on this I saw that http://www.pac4j.org/apidocs/pac4j/1.9.9/org/pac4j/core/profile/UserProfile.html also has Permissions.

I am not sure the difference between roles and permissions, but how should permissions be accessible in a RequestWrapperFilter ? 
1. Permissions are not available using RequestWrapperFilter ( if so, are permissions accessed via getUserPrincipal )
2. Permissions and roles are combined so that isUserInRole will also respond if user has permissions ( name conflicts ?)

**Comment by leleuj** [comment]
About the pac4j architecture, the `SecurityFilter` protects a URL and will internally load the profile(s) for that (if ever they exist).
So you would certainly have different `SecurityFilter` for different URLs. Be cautious though with your security configuration: following your example, /protectCAS will be accessible by an AzureAD profile: the `SecurityFilter` triggers the login process according to the clients if the user is not authenticated and grant access if the user is already authenticated (apart from the authorizations mechanism).

The way to retrieve the pac4j profiles is to use the `ProfileManager` which uses the `WebContext`.

My understanding here is that we don't want to use the `ProfileManager` and have the security/profile information available in the J2E HTTP request (migration/legacy purposes I guess). Thus, the `HttpServletRequestWrapperFilter`. It makes sense to me but we certainly need a better name.
And this filter should only be declared once (with many mappings if necessary). We don't need to choose the profile we want, it's too specific and complicated: it loads the main pac4j profile.

About the permissions, it's somehow a Shiro specific feature as indeed, it's the only library to use permissions currently.

**Comment by mores** [comment]
@leleuj 

>  (migration/legacy purposes I guess)

True - legacy apps need to be ported.

For now lets assume I am starting off a brand new JSF app...
What is the recommended way to protect a JSF app with pac4j ?

**Comment by leleuj** [comment]
Do you use CDI also? Because we have a JSF/CDI demo: https://github.com/pac4j/j2e-pac4j-cdi-demo

Exactly the same concepts, but `SecurityFilter`s are defined programmatically instead of in the `web.xml` file: https://github.com/pac4j/j2e-pac4j-cdi-demo/blob/master/src/main/java/org/pac4j/demo/j2e/WebConfig.java

**Comment by victornoel** [comment]
So in the end, I don't see why we couldn't simply have the `SecurityFilter` populate the servlet request with the correct Principal, roles and stuffs (by injecting a a request wrapper most certainly).

This is actually what is currently done in jax-rs-pac4j: we populate the jaxrs request with the correct information so that people using the jaxrs API can have the maximum of information.

**Comment by victornoel** [comment]
I can take care of doing a PR, this will be related to the one on the Principal I suppose.

**Comment by leleuj** [comment]
Yes, as we have a specific `SecurityFilter` per framework, it could really populate the web context in the appropriate way required by the current framework (J2E in that case).

Eventually, we'll certainly end up with some `HttpServletRequest` wrapping.

@victornoel I'm looking forward to your proposal on this.
