### ISSUE TITLE
branch master no longer builds

### ISSUE THREAD

**Issue by mores** [pac4j/j2e-pac4j#47]
This pull: https://github.com/pac4j/pac4j/pull/1079/files
has broken j2e-pac4j

**Comment by leleuj** [comment]
Yes, I know. The j2e-pac4j v4.0.0-SNAPSHOT is based on pac4j v3.0.0-SNAPSHOT and thus is likely to be broken. I'll fix it later on...

**Comment by leleuj** [comment]
It's fixed.
