### ISSUE TITLE
Provide a template ClientsFactory

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/j2e-pac4j#7]
Presently, the clientsFactory requires a concrete implementation; it cannot be easily instantiated via Spring and DI. It would be better if the project provided a template class that implemented the interface and accepted a number of clients via the constructor. Once we have the constructors, we can call spring to invoke the build method.

**Comment by mmoayyed** [comment]
I can provide PRs for this issue; LMK.

**Comment by leleuj** [comment]
`ClientsFactory` is an interface which must be implemented with your own clients: I'm not sure to understand where you wanna go here, but I'll be happy to review your PR...

**Comment by mmoayyed** [comment]
Suppose we had a basic implementation of the interface that accepted a list of client objects as a ctor parameter. once the object is prepped, the build method can be called to return the final list of clients. this is useful to be able to instantiate and plug in all forms of clients via spring without having to modify the code.

**Comment by leleuj** [comment]
OK. I'm waiting for your PR thus.

**Comment by mmoayyed** [comment]
Great. I am assuming you'd be able to cut a quick patch release once this is done?

**Comment by dbhankins** [comment]
I'm thinking that a class like this which allows for DI would have more general applicability than just the j2e-pac4j project; might it be appropriate to put it in pac4j-core in the package where the interface it implements lives?

**Comment by mmoayyed** [comment]
I second that idea; it helps to keep my dependencies to a minimum.

**Comment by leleuj** [comment]
I can release very often but I'd better to handle this one as well: https://github.com/pac4j/j2e-pac4j/issues/8

Everything that could be used by more than one implementation (like `j2e-pac4j`) should go into the `pac4j-core` module. So that's definitely an option.

**Comment by mmoayyed** [comment]
OK. I'll move this over to the core module

**Comment by mmoayyed** [comment]
Moved to https://github.com/pac4j/pac4j/issues/202
