### ISSUE TITLE
RequiresAuthenticationFilter/CallbackFilter via Spring

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/j2e-pac4j#8]
Allow RequiresAuthenticationFilter to be created via Spring. Rather than use of init-params, provide simple properties that spring can instantiate.

**Comment by mmoayyed** [comment]
I can provide PRs for this issue; LMK.

**Comment by leleuj** [comment]
Yes, it's currently only a filter (it's true for the `CallbackFilter` as well). It would be better indeed to make it instantiable by Spring. Please do.

**Comment by mmoayyed** [comment]
Great. Seems like we have the PR, and the next patch release should v1.1.1?

**Comment by leleuj** [comment]
Yep, I'll do the release tomorrow.

**Comment by mmoayyed** [comment]
Merged via https://github.com/pac4j/j2e-pac4j/pull/9 and https://github.com/pac4j/pac4j/pull/203
